# Generated by Django 4.0.5 on 2022-06-11 06:54

import Sapphire.models
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('About_Us_Top_Background_Image', models.ImageField(upload_to='')),
                ('About_Us_Title', models.CharField(max_length=225)),
                ('About_Us_Description', models.TextField(default='')),
                ('OurStory_Title', models.CharField(max_length=225)),
                ('Where_It_All_Began_Title', models.CharField(max_length=225)),
                ('Where_It_All_Began_Description', models.TextField(default='')),
                ('Where_It_All_Began_Image', models.ImageField(upload_to='')),
                ('Our_Mission_Title', models.CharField(max_length=225)),
                ('Our_Mission_Description', models.TextField()),
                ('Testimonial_Title', models.CharField(max_length=225)),
                ('What_People_Are_Saying_Title', models.CharField(max_length=225)),
            ],
            options={
                'verbose_name_plural': 'About',
            },
            bases=(Sapphire.models.SingleInstanceMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Background_Image', models.ImageField(upload_to='')),
                ('Title', models.CharField(max_length=255)),
                ('Description', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Contact Us',
            },
            bases=(Sapphire.models.SingleInstanceMixin, models.Model),
        ),
        migrations.CreateModel(
            name='End_Section_Of_Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Background_Image', models.ImageField(upload_to='')),
                ('logo1', models.ImageField(upload_to='')),
                ('Title1', models.CharField(max_length=225)),
                ('Descriptio1', models.CharField(max_length=225)),
                ('logo2', models.ImageField(upload_to='')),
                ('Title2', models.CharField(max_length=225)),
                ('Descriptio2', models.CharField(max_length=225)),
                ('logo3', models.ImageField(upload_to='')),
                ('Title3', models.CharField(max_length=225)),
                ('Descriptio3', models.CharField(max_length=225)),
            ],
            options={
                'verbose_name_plural': 'End_Section_Of_Products',
            },
            bases=(Sapphire.models.SingleInstanceMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Home_Top_Background_Image', models.ImageField(upload_to='')),
                ('Welcome_Title', models.CharField(max_length=225)),
                ('Welcome_Description', models.TextField()),
                ('What_We_Offer_Title', models.CharField(max_length=225)),
                ('What_We_Offer_Description', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Home',
            },
            bases=(Sapphire.models.SingleInstanceMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Our_Works',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.ImageField(upload_to='')),
            ],
            options={
                'verbose_name_plural': 'Our_Works',
            },
        ),
        migrations.CreateModel(
            name='Product_Type_1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_Name', models.CharField(max_length=225)),
                ('Product_Short_Description_1', models.CharField(max_length=225)),
                ('Product_Top_Background_Image', models.ImageField(upload_to='')),
                ('Product_Short_Description_2', models.CharField(max_length=225)),
                ('Product_Middle_Image', models.ImageField(upload_to='')),
                ('Visit_Our_Website_Title', models.CharField(blank=True, default='Visit our website', max_length=225, null=True)),
                ('Website_Link', models.URLField(blank=True, max_length=225, null=True)),
                ('To_Know_More_Visit_Our_Website', models.CharField(blank=True, default='To know more visit our website', max_length=225, null=True)),
                ('Introduction_Section_Title', models.CharField(max_length=255)),
                ('Introduction_Section_Description', models.TextField()),
                ('Introduction_Section_Image1', models.ImageField(upload_to='')),
                ('Introduction_Section_Image2', models.ImageField(upload_to='')),
                ('Why_Us_Title', models.CharField(max_length=225)),
                ('Why_Us_Description', models.TextField()),
                ('Why_Us_Image1', models.ImageField(upload_to='')),
                ('Why_Us_Image2', models.ImageField(upload_to='')),
                ('Why_Us_Image3', models.ImageField(upload_to='')),
                ('Product_Structure_Image', models.ImageField(upload_to='')),
            ],
            options={
                'verbose_name_plural': 'Product_Type_1',
            },
        ),
        migrations.CreateModel(
            name='Product_Type_2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_Name', models.CharField(max_length=225)),
                ('Product_Short_Description_1', models.CharField(max_length=225)),
                ('Product_Top_Background_Image', models.ImageField(upload_to='')),
                ('Product_Short_Description_2', models.CharField(max_length=225)),
                ('Product_Middle_Image', models.ImageField(upload_to='')),
                ('Visit_Our_Website_Title', models.CharField(blank=True, default='Visit our website', max_length=225, null=True)),
                ('Website_Link', models.URLField(blank=True, max_length=225, null=True)),
                ('To_Know_More_Visit_Our_Website', models.CharField(blank=True, default='To know more visit our website', max_length=225, null=True)),
                ('Introduction_Section_Title', models.CharField(max_length=255)),
                ('Introduction_Section_Description', models.TextField()),
                ('Introduction_Section_Image', models.ImageField(upload_to='')),
                ('Why_Us_Title', models.CharField(max_length=225)),
                ('Why_Us_Description', models.TextField()),
                ('Why_Us_Image1', models.ImageField(upload_to='')),
                ('Why_Us_Image2', models.ImageField(upload_to='')),
            ],
            options={
                'verbose_name_plural': 'Product_Type_2',
            },
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Company_Name', models.CharField(default='Sapphire Commotrade Pvt.Ltd', max_length=225)),
                ('Main_Logo', models.ImageField(upload_to='')),
                ('Office_Address_Title', models.CharField(default='Office Address', max_length=225)),
                ('Office_Address1', models.CharField(default='2nd Floor,New Golden Plaza,', max_length=225)),
                ('Office_Address2', models.CharField(default='Burdwan Road,', max_length=225)),
                ('City_1', models.CharField(default='Siliguri', max_length=64)),
                ('Office_Address_Zip_Code', models.CharField(default='734001', max_length=6)),
                ('Contact_Number_1', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('Contact_Number_2', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('Contact_Number_3', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('Offical_Email_Id', models.EmailField(max_length=254)),
                ('Offical_Information_Email_Id', models.EmailField(max_length=254)),
                ('Facebook_Page_Link', models.URLField(blank=True, max_length=225, null=True)),
                ('Instagram_Page_Link', models.URLField(blank=True, max_length=225, null=True)),
                ('Factory_Address_Title', models.CharField(default='Factory Address', max_length=255)),
                ('Factory_Address1', models.CharField(default='Demdema,Sanasekhata', max_length=255)),
                ('Factory_Address2', models.CharField(default='Bhutkihat,Rajgung,', max_length=255)),
                ('City_2', models.CharField(default='Jalpaiguri', max_length=64)),
                ('Factory_Adress_Zip_Code', models.CharField(default='735135', max_length=6)),
                ('Copyright_Field', models.CharField(default='2015 Sapphire Commotrade', max_length=225)),
                ('Footor_Logo', models.ImageField(upload_to='')),
            ],
            options={
                'verbose_name_plural': 'Settings',
            },
            bases=(Sapphire.models.SingleInstanceMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=225)),
                ('Body', models.TextField()),
                ('Full_Name', models.CharField(max_length=225)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-updated', '-created'],
            },
        ),
        migrations.CreateModel(
            name='Product_Type2_Features',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProductType2_Feature', models.CharField(blank=True, max_length=225, null=True)),
                ('Product_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sapphire.product_type_2')),
            ],
        ),
        migrations.CreateModel(
            name='Product_Type2_Assurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProductType2_Assurance', models.CharField(blank=True, max_length=225, null=True)),
                ('Product_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sapphire.product_type_2')),
            ],
        ),
        migrations.CreateModel(
            name='Product_Type1_Structure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product1_Structure_Title', models.CharField(blank=True, max_length=225, null=True)),
                ('Product1_Structure_Short_Description', models.TextField(blank=True, null=True)),
                ('Product_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sapphire.product_type_1')),
            ],
        ),
        migrations.CreateModel(
            name='Product_Type1_Features',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProductType1_Feature', models.CharField(blank=True, max_length=225, null=True)),
                ('Product_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sapphire.product_type_1')),
            ],
        ),
        migrations.CreateModel(
            name='Product_Type1_Assurances',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProductType1_Assurance', models.CharField(blank=True, max_length=225, null=True)),
                ('Product_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sapphire.product_type_1')),
            ],
        ),
    ]
