# Generated by Django 3.2.12 on 2022-06-20 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sapphire', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={'verbose_name_plural': '      About'},
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name_plural': ' Contact Us'},
        ),
        migrations.AlterModelOptions(
            name='home',
            options={'verbose_name_plural': '       Home'},
        ),
        migrations.AlterModelOptions(
            name='our_works',
            options={'verbose_name_plural': '  Our_Works'},
        ),
        migrations.AlterModelOptions(
            name='product_type_1',
            options={'verbose_name_plural': '    Product_Type_1'},
        ),
        migrations.AlterModelOptions(
            name='product_type_2',
            options={'verbose_name_plural': '   Product_Type_2'},
        ),
        migrations.AlterModelOptions(
            name='settings',
            options={'verbose_name_plural': '        Settings'},
        ),
        migrations.AlterModelOptions(
            name='testimonial',
            options={'ordering': ['-updated', '-created'], 'verbose_name_plural': '     Testimonials'},
        ),
        migrations.AlterField(
            model_name='our_works',
            name='Image1',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='our_works',
            name='Image2',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='our_works',
            name='Image3',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
