# Generated by Django 3.2.14 on 2022-08-17 08:06

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('Sapphire', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrochurePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_Name', models.CharField(blank=True, max_length=255)),
                ('document', models.FileField(upload_to='static/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'BrochurePage',
            },
        ),
        migrations.CreateModel(
            name='Customer_InfoPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FullName', models.CharField(max_length=200)),
                ('Phone_Number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('Email', models.EmailField(max_length=254)),
                ('Subject', models.CharField(max_length=500, null=True)),
                ('State', models.CharField(max_length=200)),
                ('Message', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Customer_InfoPage',
            },
        ),
    ]
