# Generated by Django 4.0.5 on 2022-06-11 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sapphire', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='end_section_of_products',
            name='Descriptio1',
        ),
        migrations.RemoveField(
            model_name='end_section_of_products',
            name='Descriptio2',
        ),
        migrations.RemoveField(
            model_name='end_section_of_products',
            name='Descriptio3',
        ),
        migrations.AddField(
            model_name='end_section_of_products',
            name='Description1',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='end_section_of_products',
            name='Description2',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='end_section_of_products',
            name='Description3',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
    ]
