# Generated by Django 4.0.5 on 2022-06-11 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sapphire', '0002_remove_end_section_of_products_descriptio1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_type1_structure',
            name='Product1_Structure_Title',
            field=models.CharField(blank=True, default='', max_length=225, null=True),
        ),
    ]
