# Generated by Django 3.2.12 on 2022-06-25 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sapphire', '0002_auto_20220620_2313'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_type_1',
            name='Product_HomePage_Image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='product_type_1',
            name='Product_ProductPage_Image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='product_type_2',
            name='Product_HomePage_Image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='product_type_2',
            name='Product_ProductPage_Image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
