# Generated by Django 3.2.14 on 2022-08-27 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sapphire', '0003_alter_customer_infopage_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer_infopage',
            name='Sent',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
