# Generated by Django 3.2.12 on 2022-08-02 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sapphire', '0003_auto_20220625_2222'),
        ('Sapphire', '0003_product_type_1_product_homepage_image_and_more'),
    ]

    operations = [
    ]
