# Generated by Django 4.0.5 on 2022-06-13 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sapphire', '0003_alter_product_type1_structure_product1_structure_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_type_1',
            name='Product_HomePage_Description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product_type_1',
            name='Product_ProductPage_Description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product_type_2',
            name='Product_HomePage_Description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product_type_2',
            name='Product_ProductPage_Description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
