# Generated by Django 3.2.14 on 2022-08-02 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sapphire', '0003_product_type_1_product_homepage_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_type_1',
            name='Product_Name',
            field=models.SlugField(max_length=200, null=True),
        ),
    ]
