# Generated by Django 3.2.14 on 2022-08-29 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sapphire', '0004_customer_infopage_sent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer_infopage',
            name='State',
        ),
        migrations.RemoveField(
            model_name='customer_infopage',
            name='Subject',
        ),
    ]
