# Generated by Django 4.0.5 on 2022-06-13 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sapphire', '0004_product_type_1_product_homepage_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='Contact_Title',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='Email_Title',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
    ]
