# Generated by Django 3.2.14 on 2022-08-02 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sapphire', '0005_auto_20220802_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_type_1',
            name='Product_Name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product_type_2',
            name='Product_Name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
