# Generated by Django 3.2.14 on 2022-08-02 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sapphire', '0006_auto_20220802_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_type_1',
            name='Product_Name',
            field=models.CharField(max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name='product_type_2',
            name='Product_Name',
            field=models.CharField(max_length=225, null=True),
        ),
    ]
