# Generated by Django 3.2.14 on 2022-08-05 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sapphire', '0008_auto_20220805_0136'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settings',
            name='LinkedIn_Page_Link',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='Twitter_Page_Link',
        ),
    ]
