# Generated by Django 3.2.12 on 2022-08-05 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sapphire', '0004_merge_20220802_0359'),
        ('Sapphire', '0008_auto_20220805_0136'),
    ]

    operations = [
    ]
