# Generated by Django 3.2.14 on 2022-08-05 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sapphire', '0009_auto_20220805_0248'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='LinkedIn_Link',
            field=models.URLField(blank=True, max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='Twitter_Link',
            field=models.URLField(blank=True, max_length=225, null=True),
        ),
    ]
