# Generated by Django 3.2.12 on 2022-08-05 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sapphire', '0009_merge_20220805_0213'),
        ('Sapphire', '0010_auto_20220805_0250'),
    ]

    operations = [
    ]
