# Generated by Django 3.2.14 on 2022-08-05 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sapphire', '0010_auto_20220805_0250'),
    ]

    operations = [
        migrations.RenameField(
            model_name='settings',
            old_name='LinkedIn_Link',
            new_name='LinkedIn_Page_Link',
        ),
        migrations.RenameField(
            model_name='settings',
            old_name='Twitter_Link',
            new_name='Twitter_Page_Link',
        ),
    ]
