# Generated by Django 3.2.12 on 2022-08-05 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sapphire', '0011_auto_20220805_0303'),
        ('Sapphire', '0011_merge_20220805_0258'),
    ]

    operations = [
    ]
