# Generated by Django 3.2.12 on 2022-08-05 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sapphire', '0012_auto_20220805_0357'),
        ('Sapphire', '0012_merge_20220805_0311'),
    ]

    operations = [
    ]
