# Generated by Django 3.2.12 on 2022-08-05 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sapphire', '0013_auto_20220805_0409'),
        ('Sapphire', '0013_merge_20220805_0401'),
    ]

    operations = [
    ]
