# Generated by Django 3.2.14 on 2022-08-05 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sapphire', '0013_auto_20220805_0409'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settings',
            name='LinkedIn_Page_Link',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='Twitter_Page_Link',
        ),
    ]
