# Generated by Django 3.2.12 on 2022-08-05 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sapphire', '0014_auto_20220805_0420'),
        ('Sapphire', '0014_merge_20220805_0414'),
    ]

    operations = [
    ]
