# Generated by Django 3.2.12 on 2022-08-05 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sapphire', '0015_merge_20220805_0431'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='LinkedIn_Page_Link',
            field=models.URLField(blank=True, max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='Twitter_Page_Link',
            field=models.URLField(blank=True, max_length=225, null=True),
        ),
    ]
